[build]
  command = "echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_API_KEY && echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_AUTH_DOMAIN && echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_PROJECT_ID && echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_STORAGE_BUCKET && echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_MESSAGING_SENDER_ID && echo $REACT_APP_MULTIPAGE_MOVIE_FIREBASE_DB_APP_ID && npm run build"
  publish = "build"
