[build]
  command = "echo $MULTIPAGE_FIREBASE_MOVIE_DB_API_KEY && echo $MULTIPAGE_FIREBASE_MOVIE_DB_AUTH_DOMAIN && echo $MULTIPAGE_FIREBASE_MOVIE_DB_PROJECT_ID && echo $MULTIPAGE_FIREBASE_MOVIE_DB_STORAGE_BUCKET && echo $MULTIPAGE_FIREBASE_MOVIE_DB_MESSAGING_SENDER_ID && echo $MULTIPAGE_FIREBASE_MOVIE_DB_APP_ID && npm run build"
  publish = "build"
