name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          MULTIPAGE_FIREBASE_MOVIE_DB_API_KEY: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_API_KEY }}
          MULTIPAGE_FIREBASE_MOVIE_DB_AUTH_DOMAIN: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_AUTH_DOMAIN }}
          MULTIPAGE_FIREBASE_MOVIE_DB_PROJECT_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_PROJECT_ID }}
          MULTIPAGE_FIREBASE_MOVIE_DB_STORAGE_BUCKET: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_STORAGE_BUCKET }}
          MULTIPAGE_FIREBASE_MOVIE_DB_MESSAGING_SENDER_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_MESSAGING_SENDER_ID }}
          MULTIPAGE_FIREBASE_MOVIE_DB_APP_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_APP_ID }}

      - name: Deploy
        run: npm run deploy
        env:
          MULTIPAGE_FIREBASE_MOVIE_DB_API_KEY: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_API_KEY }}
          MULTIPAGE_FIREBASE_MOVIE_DB_AUTH_DOMAIN: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_AUTH_DOMAIN }}
          MULTIPAGE_FIREBASE_MOVIE_DB_PROJECT_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_PROJECT_ID }}
          MULTIPAGE_FIREBASE_MOVIE_DB_STORAGE_BUCKET: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_STORAGE_BUCKET }}
          MULTIPAGE_FIREBASE_MOVIE_DB_MESSAGING_SENDER_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_MESSAGING_SENDER_ID }}
          MULTIPAGE_FIREBASE_MOVIE_DB_APP_ID: ${{ secrets.MULTIPAGE_FIREBASE_MOVIE_DB_APP_ID }}
